import {
    AbilityAnimations,
    Animations,
    Assets,
    GroundAnimations,
    SynergyAnimations,
} from "./constants";

type AnimationsConfig = {
    key: string;
    assetKey: Assets;
    startFrame: number;
    endFrame: number;
    frameRate: number;
    repeat: number;
    prefix: string;
    suffix: string;
}[];

const baseAnimations: AnimationsConfig = [
    {
        key: Animations.Invalid,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "/",
        suffix: ".png",
    },
    {
        key: Animations.MinotaurIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "minotaur/",
        suffix: ".png",
    },
    {
        key: Animations.ColossusIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "colossus/",
        suffix: ".png",
    },
    {
        key: Animations.BehemothIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "behemoth/",
        suffix: ".png",
    },
    {
        key: Animations.WyvernIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "wyvern/",
        suffix: ".png",
    },
    {
        key: Animations.BerserkerIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "berserker/",
        suffix: ".png",
    },
    {
        key: Animations.GolemIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "golem/",
        suffix: ".png",
    },
    {
        key: Animations.BearIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "bear/",
        suffix: ".png",
    },
    {
        key: Animations.KitsuneIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "kitsune/",
        suffix: ".png",
    },
    {
        key: Animations.NueIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "nue/",
        suffix: ".png",
    },
    {
        key: Animations.CyclopsIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "cyclops/",
        suffix: ".png",
    },
    {
        key: Animations.WraithIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "wraith/",
        suffix: ".png",
    },
    {
        key: Animations.FairyIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "fairy/",
        suffix: ".png",
    },
    {
        key: Animations.LeprechaunIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "leprechaun/",
        suffix: ".png",
    },
    {
        key: Animations.DragonIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "dragon/",
        suffix: ".png",
    },
    {
        key: Animations.WendigoIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "wendigo/",
        suffix: ".png",
    },
    {
        key: Animations.RakshasaIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "rakshasa/",
        suffix: ".png",
    },
    {
        key: Animations.VampireIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "vampire/",
        suffix: ".png",
    },
    {
        key: Animations.FenrirIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "fenrir/",
        suffix: ".png",
    },
    {
        key: Animations.OgreIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "ogre/",
        suffix: ".png",
    },
    {
        key: Animations.WarlockIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "warlock/",
        suffix: ".png",
    },
    {
        key: Animations.JiangshiIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "jiangshi/",
        suffix: ".png",
    },
    {
        key: Animations.TarrasqueIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "tarrasque/",
        suffix: ".png",
    },
    {
        key: Animations.ChupacabraIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "chupacabra/",
        suffix: ".png",
    },
    {
        key: Animations.EttinIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "ettin/",
        suffix: ".png",
    },
    {
        key: Animations.SatoriIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "satori/",
        suffix: ".png",
    },
    {
        key: Animations.MantisIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "mantis/",
        suffix: ".png",
    },
    {
        key: Animations.OrcIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "orc/",
        suffix: ".png",
    },
    {
        key: Animations.BasiliskIdle,
        assetKey: Assets.MainAtlas,
        startFrame: 0,
        endFrame: 0,
        frameRate: 1,
        repeat: -1,
        prefix: "basilisk/",
        suffix: ".png",
    },
    {
        key: AbilityAnimations.burningBurst,
        assetKey: Assets.AbilityAtlas,
        startFrame: 0,
        endFrame: 11,
        frameRate: 8,
        repeat: 0,
        prefix: "burningBurst/",
        suffix: ".png",
    },
    {
        key: AbilityAnimations.barbariansRage,
        assetKey: Assets.AbilityAtlas,
        startFrame: 0,
        endFrame: 16,
        frameRate: 8,
        repeat: 0,
        prefix: "barbariansRage/",
        suffix: ".png",
    },
    {
        key: AbilityAnimations.mountainCollapse,
        assetKey: Assets.AbilityAtlas,
        startFrame: 0,
        endFrame: 9,
        frameRate: 8,
        repeat: 0,
        prefix: "mountainCollapse/",
        suffix: ".png",
    },
    {
        key: GroundAnimations.fire,
        assetKey: Assets.GroundAtlas,
        startFrame: 0,
        endFrame: 7,
        frameRate: 8,
        repeat: -1,
        prefix: "fire/",
        suffix: ".png",
    },
    {
        key: GroundAnimations.slightFire,
        assetKey: Assets.GroundAtlas,
        startFrame: 0,
        endFrame: 7,
        frameRate: 8,
        repeat: 0,
        prefix: "fire/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.hunter,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 3,
        frameRate: 4,
        repeat: 0,
        prefix: "hunter/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.imaginary,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 18,
        frameRate: 19,
        repeat: 0,
        prefix: "imaginary/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.dark,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 14,
        frameRate: 15,
        repeat: 0,
        prefix: "dark/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.magical,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 7,
        frameRate: 8,
        repeat: 0,
        prefix: "magical/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.strength,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 9,
        frameRate: 10,
        repeat: 0,
        prefix: "strength/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.light,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 15,
        frameRate: 16,
        repeat: 0,
        prefix: "light/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.brute,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 6,
        frameRate: 7,
        repeat: 0,
        prefix: "brute/",
        suffix: ".png",
    },
    {
        key: SynergyAnimations.cunning,
        assetKey: Assets.SynergyAtlas,
        startFrame: 0,
        endFrame: 6,
        frameRate: 7,
        repeat: 0,
        prefix: "cunning/",
        suffix: ".png",
    },
];

export function getAnimations() {
    // const animationConfigs: AnimationsConfig = [];
    return baseAnimations;
}
