// This file is auto-generated by generateWhitelistHashes.ts
// DO NOT EDIT DIRECTLY

export const whitelistedHashes: string[] = [
    "0x2917789a9bdf8816372c5563cc384c57f18283c45ed4839cfa7e65832d705a7", // 0x061aaefa3a5025ff8350642b71328a2eb0c9cdddc6f9aed360ebd39dba481eec
];
