// This file is auto-generated by generateWhitelistHashes.ts
// DO NOT EDIT DIRECTLY

export const whitelistedHashes: string[] = [
    "0x2917789a9bdf8816372c5563cc384c57f18283c45ed4839cfa7e65832d705a7", // 0x061aaefa3a5025ff8350642b71328a2eb0c9cdddc6f9aed360ebd39dba481eec
    "0x4b8861714b036b2b6e5b0f3bfbc0b4e7f07320e90bfc48ade2a19ae89812dc6", // 0x045ff6b6c2f30937941b1482ad478b3e7176e3d2335f2b9987a8417fb30b99b3
];
