# fly.toml app configuration file generated for zenith-katana on 2024-07-10T21:25:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zenith-katana'
primary_region = 'hkg'
swap_size_mb = 512

[mounts]
source = "katana_db"
destination = "/data"
initial_size = "1GB"
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "5GB"
auto_extend_size_threshold = 80


[build]
dockerfile = "katana.Dockerfile"

[http_service]
internal_port = 5050
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 0
processes = ['app']


[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
